defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: superfit
  timeout: 5000
  username: superfit
  password:

development:
  <<: *defaults
  host: localhost

test:
  <<: *defaults
  database: superfit_test

production:
  <<: *defaults
  host: localhost